/* demo-backend.js — in-browser stand-in for the local Python server.
   Generated by make_webdemo.py; do not edit the copy in webdemo/ directly.

   Intercepts every fetch("/api/...") the unmodified app.js makes and answers
   it client-side: CSV parsing, the practice-mode simulated AI, and the belief
   -elicitation job runner. Real AI providers are disabled in the web demo. */
"use strict";

(() => {
  const REGISTRY = {
  "providers": {
    "openai": {
      "label": "ChatGPT (OpenAI)",
      "key_hint": "Starts with \u201csk-\u2026\u201d \u2014 from platform.openai.com \u2192 API keys",
      "models": [
        {
          "id": "gpt-5.6-sol",
          "label": "GPT-5.6 Sol",
          "note": "most capable",
          "efforts": [
            {
              "id": "none",
              "label": "None (fastest)"
            },
            {
              "id": "low",
              "label": "Low"
            },
            {
              "id": "medium",
              "label": "Medium (default)"
            },
            {
              "id": "high",
              "label": "High"
            },
            {
              "id": "xhigh",
              "label": "Extra high"
            },
            {
              "id": "max",
              "label": "Maximum (slowest)"
            }
          ],
          "default_effort": "medium"
        },
        {
          "id": "gpt-5.6-terra",
          "label": "GPT-5.6 Terra",
          "note": "balanced",
          "efforts": [
            {
              "id": "none",
              "label": "None (fastest)"
            },
            {
              "id": "low",
              "label": "Low"
            },
            {
              "id": "medium",
              "label": "Medium (default)"
            },
            {
              "id": "high",
              "label": "High"
            },
            {
              "id": "xhigh",
              "label": "Extra high"
            },
            {
              "id": "max",
              "label": "Maximum (slowest)"
            }
          ],
          "default_effort": "medium"
        },
        {
          "id": "gpt-5.6-luna",
          "label": "GPT-5.6 Luna",
          "note": "fastest / lowest cost",
          "efforts": [
            {
              "id": "none",
              "label": "None (fastest)"
            },
            {
              "id": "low",
              "label": "Low"
            },
            {
              "id": "medium",
              "label": "Medium (default)"
            },
            {
              "id": "high",
              "label": "High"
            },
            {
              "id": "xhigh",
              "label": "Extra high"
            },
            {
              "id": "max",
              "label": "Maximum (slowest)"
            }
          ],
          "default_effort": "medium"
        },
        {
          "id": "gpt-5.5-pro",
          "label": "GPT-5.5 Pro",
          "note": "deep reasoning, slow",
          "efforts": [
            {
              "id": "medium",
              "label": "Medium"
            },
            {
              "id": "high",
              "label": "High (default)"
            },
            {
              "id": "xhigh",
              "label": "Extra high (slowest)"
            }
          ],
          "default_effort": "high"
        },
        {
          "id": "gpt-5.4",
          "label": "GPT-5.4",
          "note": "previous generation",
          "efforts": [
            {
              "id": "none",
              "label": "None (default, fastest)"
            },
            {
              "id": "low",
              "label": "Low"
            },
            {
              "id": "medium",
              "label": "Medium"
            },
            {
              "id": "high",
              "label": "High"
            },
            {
              "id": "xhigh",
              "label": "Extra high (slowest)"
            }
          ],
          "default_effort": "medium"
        },
        {
          "id": "gpt-5.4-mini",
          "label": "GPT-5.4 mini",
          "note": "small, low cost",
          "efforts": [
            {
              "id": "none",
              "label": "None (default, fastest)"
            },
            {
              "id": "low",
              "label": "Low"
            },
            {
              "id": "medium",
              "label": "Medium"
            },
            {
              "id": "high",
              "label": "High"
            },
            {
              "id": "xhigh",
              "label": "Extra high (slowest)"
            }
          ],
          "default_effort": "medium"
        },
        {
          "id": "gpt-5.4-nano",
          "label": "GPT-5.4 nano",
          "note": "smallest, lowest cost",
          "efforts": [
            {
              "id": "none",
              "label": "None (default, fastest)"
            },
            {
              "id": "low",
              "label": "Low"
            },
            {
              "id": "medium",
              "label": "Medium"
            },
            {
              "id": "high",
              "label": "High"
            },
            {
              "id": "xhigh",
              "label": "Extra high (slowest)"
            }
          ],
          "default_effort": "medium"
        }
      ]
    },
    "anthropic": {
      "label": "Claude (Anthropic)",
      "key_hint": "Starts with \u201csk-ant-\u2026\u201d \u2014 from console.anthropic.com \u2192 API keys",
      "models": [
        {
          "id": "claude-fable-5",
          "label": "Claude Fable 5",
          "note": "most capable",
          "efforts": [
            {
              "id": "low",
              "label": "Low (fastest)"
            },
            {
              "id": "medium",
              "label": "Medium"
            },
            {
              "id": "high",
              "label": "High (default)"
            },
            {
              "id": "xhigh",
              "label": "Extra high"
            },
            {
              "id": "max",
              "label": "Maximum (slowest)"
            }
          ],
          "default_effort": "high"
        },
        {
          "id": "claude-opus-5",
          "label": "Claude Opus 5",
          "note": "very capable",
          "efforts": [
            {
              "id": "low",
              "label": "Low (fastest)"
            },
            {
              "id": "medium",
              "label": "Medium"
            },
            {
              "id": "high",
              "label": "High (default)"
            },
            {
              "id": "xhigh",
              "label": "Extra high"
            },
            {
              "id": "max",
              "label": "Maximum (slowest)"
            }
          ],
          "default_effort": "high"
        },
        {
          "id": "claude-sonnet-5",
          "label": "Claude Sonnet 5",
          "note": "balanced",
          "efforts": [
            {
              "id": "low",
              "label": "Low (fastest)"
            },
            {
              "id": "medium",
              "label": "Medium"
            },
            {
              "id": "high",
              "label": "High (default)"
            },
            {
              "id": "xhigh",
              "label": "Extra high"
            },
            {
              "id": "max",
              "label": "Maximum (slowest)"
            }
          ],
          "default_effort": "high"
        },
        {
          "id": "claude-haiku-4-5",
          "label": "Claude Haiku 4.5",
          "note": "fastest / lowest cost",
          "efforts": [
            {
              "id": "off",
              "label": "Off (fastest)"
            },
            {
              "id": "low",
              "label": "Low (2k thinking tokens)"
            },
            {
              "id": "medium",
              "label": "Medium (8k thinking tokens)"
            },
            {
              "id": "high",
              "label": "High (16k thinking tokens)"
            }
          ],
          "default_effort": "medium"
        },
        {
          "id": "claude-opus-4-8",
          "label": "Claude Opus 4.8",
          "note": "previous generation",
          "efforts": [
            {
              "id": "low",
              "label": "Low (fastest)"
            },
            {
              "id": "medium",
              "label": "Medium"
            },
            {
              "id": "high",
              "label": "High (default)"
            },
            {
              "id": "xhigh",
              "label": "Extra high"
            },
            {
              "id": "max",
              "label": "Maximum (slowest)"
            }
          ],
          "default_effort": "high"
        },
        {
          "id": "claude-sonnet-4-6",
          "label": "Claude Sonnet 4.6",
          "note": "previous generation",
          "efforts": [
            {
              "id": "low",
              "label": "Low (fastest)"
            },
            {
              "id": "medium",
              "label": "Medium"
            },
            {
              "id": "high",
              "label": "High (default)"
            },
            {
              "id": "max",
              "label": "Maximum (slowest)"
            }
          ],
          "default_effort": "high"
        }
      ]
    },
    "google": {
      "label": "Gemini (Google)",
      "key_hint": "From aistudio.google.com \u2192 Get API key",
      "models": [
        {
          "id": "gemini-3.7-flash",
          "label": "Gemini 3.7 Flash",
          "note": "newest, fast",
          "efforts": [
            {
              "id": "low",
              "label": "Low (fastest)"
            },
            {
              "id": "medium",
              "label": "Medium (default)"
            },
            {
              "id": "high",
              "label": "High (slowest)"
            }
          ],
          "default_effort": "medium"
        },
        {
          "id": "gemini-3.6-flash",
          "label": "Gemini 3.6 Flash",
          "note": "fast",
          "efforts": [
            {
              "id": "low",
              "label": "Low (fastest)"
            },
            {
              "id": "medium",
              "label": "Medium (default)"
            },
            {
              "id": "high",
              "label": "High (slowest)"
            }
          ],
          "default_effort": "medium"
        },
        {
          "id": "gemini-3.1-pro-preview",
          "label": "Gemini 3.1 Pro",
          "note": "most capable (preview)",
          "efforts": [
            {
              "id": "low",
              "label": "Low (fastest)"
            },
            {
              "id": "medium",
              "label": "Medium (default)"
            },
            {
              "id": "high",
              "label": "High (slowest)"
            }
          ],
          "default_effort": "high"
        },
        {
          "id": "gemini-3.5-flash",
          "label": "Gemini 3.5 Flash",
          "note": "fast",
          "efforts": [
            {
              "id": "low",
              "label": "Low (fastest)"
            },
            {
              "id": "medium",
              "label": "Medium (default)"
            },
            {
              "id": "high",
              "label": "High (slowest)"
            }
          ],
          "default_effort": "medium"
        },
        {
          "id": "gemini-3.5-flash-lite",
          "label": "Gemini 3.5 Flash-Lite",
          "note": "lowest cost",
          "efforts": [
            {
              "id": "low",
              "label": "Low (fastest)"
            },
            {
              "id": "medium",
              "label": "Medium (default)"
            },
            {
              "id": "high",
              "label": "High (slowest)"
            }
          ],
          "default_effort": "low"
        },
        {
          "id": "gemini-2.5-pro",
          "label": "Gemini 2.5 Pro",
          "note": "previous generation",
          "efforts": [
            {
              "id": "low",
              "label": "Low (1k thinking tokens)"
            },
            {
              "id": "medium",
              "label": "Medium (8k thinking tokens)"
            },
            {
              "id": "high",
              "label": "High (24k thinking tokens)"
            }
          ],
          "default_effort": "medium"
        },
        {
          "id": "gemini-2.5-flash",
          "label": "Gemini 2.5 Flash",
          "note": "previous generation",
          "efforts": [
            {
              "id": "off",
              "label": "Off (fastest)"
            },
            {
              "id": "low",
              "label": "Low (1k thinking tokens)"
            },
            {
              "id": "medium",
              "label": "Medium (8k thinking tokens)"
            },
            {
              "id": "high",
              "label": "High (24k thinking tokens)"
            }
          ],
          "default_effort": "medium"
        }
      ]
    },
    "demo": {
      "label": "Practice mode (no API key needed)",
      "key_hint": "No key needed \u2014 generates simulated answers so you can try the tool",
      "models": [
        {
          "id": "demo-model",
          "label": "Simulated AI (for practice only)",
          "note": "not a real AI \u2014 do not use for real analysis",
          "efforts": [
            {
              "id": "n/a",
              "label": "Not applicable"
            }
          ],
          "default_effort": "n/a"
        }
      ]
    }
  }
};

  const WEB_DEMO_MSG =
    "This web page is a demo and cannot contact real AI providers. " +
    "Choose “Practice mode” here to see the full workflow with a simulated AI — " +
    "or use the free downloadable tool to run ChatGPT, Claude, or Gemini on your own data.";

  const FORMAT_INSTRUCTION =
    "Answer in exactly this format, with no other text:\n\n" +
    "PROBABILITY: <a single number between 0 and 1>";

  const TRUE_TOKENS = new Set(["1", "1.0", "yes", "y", "true", "t", "positive", "pos", "admit"]);

  const datasets = new Map();
  const jobs = new Map();
  let nextId = 1;

  /* ---------------- CSV parsing (quoted fields, CRLF, BOM) ---------------- */

  function parseCsv(text) {
    if (text.charCodeAt(0) === 0xfeff) text = text.slice(1);
    const rows = [];
    let field = "", row = [], inQuotes = false;
    for (let i = 0; i < text.length; i++) {
      const ch = text[i];
      if (inQuotes) {
        if (ch === '"') {
          if (text[i + 1] === '"') { field += '"'; i++; }
          else inQuotes = false;
        } else field += ch;
      } else if (ch === '"') inQuotes = true;
      else if (ch === ",") { row.push(field); field = ""; }
      else if (ch === "\n" || ch === "\r") {
        if (ch === "\r" && text[i + 1] === "\n") i++;
        row.push(field); field = "";
        rows.push(row); row = [];
      } else field += ch;
    }
    if (field !== "" || row.length) { row.push(field); rows.push(row); }
    const nonEmpty = rows.filter((r) => r.some((c) => c.trim() !== ""));
    if (nonEmpty.length < 2) throw new Error("The file needs a header row and at least one data row.");
    const columns = nonEmpty[0].map((c) => c.trim());
    const data = nonEmpty.slice(1).map((r) => {
      const obj = {};
      columns.forEach((c, i) => { obj[c] = (r[i] || "").trim(); });
      return obj;
    });
    return { columns, rows: data };
  }

  /* ---------------- Simulated AI (mirrors providers._query_demo) ---------------- */

  async function sha256hex(text) {
    const buf = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(text));
    return [...new Uint8Array(buf)].map((b) => b.toString(16).padStart(2, "0")).join("");
  }

  async function demoBelief(prompt, demoLabel) {
    const h = parseInt((await sha256hex(prompt)).slice(0, 8), 16);
    const noise = (h % 1000) / 1000;
    const base = demoLabel === 1 ? 0.15 + 0.72 * noise : 0.02 + 0.55 * noise;
    return Math.min(0.99, Math.max(0.01, Math.pow(base, 0.65)));
  }

  const buildPrompt = (context, question) =>
    `${context.trim()}\n\n${question.trim()}\n\n${FORMAT_INSTRUCTION}`;

  /* ---------------- Job runner ---------------- */

  function buildContext(row, contextCols) {
    if (contextCols.length === 1) return row[contextCols[0]] || "";
    return contextCols.map((c) => (row[c] ? `${c}: ${row[c]}` : "")).filter(Boolean).join("\n");
  }

  function startJob(cfg) {
    if (cfg.provider !== "demo") throw new Error(WEB_DEMO_MSG);
    const ds = datasets.get(cfg.dataset_id);
    if (!ds) throw new Error("Please re-load your file (the page was refreshed).");
    const positive = new Set(cfg.positive_values);
    const cases = [];
    ds.rows.forEach((row, i) => {
      const raw = (row[cfg.outcome_col] || "").trim();
      const context = buildContext(row, cfg.context_cols);
      if (raw === "" || context.trim() === "") return;
      if (cfg.limit && cases.length >= cfg.limit) return;
      cases.push({ index: i, context, label: positive.has(raw) ? 1 : 0 });
    });
    if (!cases.length) throw new Error("No usable rows: every row needs patient information and an outcome value.");

    const job = {
      id: String(nextId++), status: "running", total: cases.length,
      done: 0, failed: 0, cancel: false,
      config: {
        provider: cfg.provider, model: cfg.model, effort: cfg.effort,
        belief_question: cfg.belief_question, decision_question: cfg.decision_question,
      },
      results: cases.map((c) => ({
        index: c.index, label: c.label, belief: null, error: null,
        context_preview: c.context.slice(0, 160),
      })),
    };
    jobs.set(job.id, job);

    (async () => {
      for (let pos = 0; pos < cases.length; pos++) {
        if (job.cancel) break;
        const prompt = buildPrompt(cases[pos].context, cfg.belief_question);
        job.results[pos].belief = await demoBelief(prompt, cases[pos].label);
        job.done++;
        if (pos % 3 === 2) await new Promise((r) => setTimeout(r, 30)); // visible progress
      }
      job.done = job.cancel ? job.done : job.total;
      job.status = job.cancel ? "cancelled" : "finished";
    })();
    return job.id;
  }

  const jobState = (job) => ({
    id: job.id, status: job.status, total: job.total, done: job.done,
    failed: job.failed, config: job.config,
    ...(job.status !== "running" ? { results: job.results } : {}),
  });

  /* ---------------- Route table ---------------- */

  const json = (obj, status = 200) =>
    new Response(JSON.stringify(obj), { status, headers: { "Content-Type": "application/json" } });
  const err = (message, status = 400) => json({ error: message }, status);

  async function route(url, opts) {
    const body = opts && opts.body ? JSON.parse(opts.body) : {};
    const jobMatch = url.match(/^\/api\/job\/([^/]+)(\/cancel)?$/);

    if (url === "/api/providers") return json(REGISTRY);
    if (url === "/api/sample_dataset") return fetch("sample_patients.csv");
    if (url === "/api/dataset") {
      try {
        const parsed = parseCsv(body.csv_text);
        const id = String(nextId++);
        datasets.set(id, parsed);
        return json({ dataset_id: id, columns: parsed.columns,
                      n_rows: parsed.rows.length, preview: parsed.rows.slice(0, 5) });
      } catch (e) { return err(e.message); }
    }
    if (url === "/api/dataset/values") {
      const ds = datasets.get(body.dataset_id);
      if (!ds) return err("Please re-load your file (the page was refreshed).", 404);
      const counts = new Map();
      for (const row of ds.rows) {
        const v = (row[body.column] || "").trim();
        counts.set(v, (counts.get(v) || 0) + 1);
      }
      const ordered = [...counts.entries()].sort((a, b) => b[1] - a[1]).slice(0, 25);
      const guess = ordered.map(([v]) => v).filter((v) => TRUE_TOKENS.has(v.toLowerCase()));
      return json({
        values: ordered.map(([value, count]) => ({ value, count })),
        n_distinct: counts.size,
        suggested_positive: guess.slice(0, 1),
      });
    }
    if (url === "/api/test_connection") {
      if (body.provider !== "demo") return err(WEB_DEMO_MSG, 502);
      return json({ ok: true, reply: "PROBABILITY: 0.5" });
    }
    if (url === "/api/run") {
      try { return json({ job_id: startJob(body) }); }
      catch (e) { return err(e.message); }
    }
    if (jobMatch && jobMatch[2]) {          // POST /api/job/{id}/cancel
      const job = jobs.get(jobMatch[1]);
      if (!job) return err("Unknown job.", 404);
      job.cancel = true;
      return json({ ok: true });
    }
    if (jobMatch) {                          // GET /api/job/{id}
      const job = jobs.get(jobMatch[1]);
      if (!job) return err("Unknown job.", 404);
      return json(jobState(job));
    }
    if (url === "/api/decide") {
      if (body.provider !== "demo") return err(WEB_DEMO_MSG, 502);
      const prompt = buildPrompt(body.context, body.belief_question);
      const h = parseInt((await sha256hex(body.context)).slice(0, 8), 16);
      const belief = await demoBelief(prompt, h % 2);
      return json({ belief, threshold: body.threshold,
                    decision: belief >= Number(body.threshold), raw: `PROBABILITY: ${belief.toFixed(2)}` });
    }
    return err("Not found.", 404);
  }

  /* ---------------- fetch interception + CSV download ---------------- */

  const realFetch = window.fetch.bind(window);
  window.fetch = (url, opts) => {
    if (typeof url === "string" && url.startsWith("/api/")) return route(url, opts);
    return realFetch(url, opts);
  };

  document.addEventListener("click", (evt) => {
    const a = evt.target.closest && evt.target.closest("#download-beliefs");
    if (!a) return;
    evt.preventDefault();
    const m = (a.getAttribute("href") || "").match(/^\/api\/job\/([^/]+)\/beliefs\.csv$/);
    const job = m && jobs.get(m[1]);
    if (!job) return;
    const lines = ["row_number,belief,label,error"];
    for (const r of job.results) {
      lines.push(`${r.index + 1},${r.belief === null ? "" : r.belief.toFixed(4)},${r.label},`);
    }
    const blob = new Blob([lines.join("\n") + "\n"], { type: "text/csv" });
    const tmp = document.createElement("a");
    tmp.href = URL.createObjectURL(blob);
    tmp.download = "ai_beliefs.csv";
    tmp.click();
    URL.revokeObjectURL(tmp.href);
  }, true);
})();
